sudo: required
language: generic

services:
  - docker

before_install:
  - docker build --tag ggabmc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ggabmc/docker-react npm run test

# deploy to aws elasticbeanstalk
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'docker-react-env'
  bucket_name: 'elasticbeanstalk-us-east-1-063903771411'
  bucket_path: 'docker-react'
  on:
    branch: master

  # User("docker-react-travis-ci") (IAM) Access keys 
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: $AWS_SECRET_KEY