sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t ggabmc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ggabmc/docker-react npm run test

# deploy to aws elasticbeanstalk
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'docker-web-app'
#   env: 'docker-web-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-063903771411'
#   bucket_path: 'docker-web-app'
#   on:
#     branch: master

#   # User("docker-react-travis-ci") (IAM) Access keys 
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY