version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - CHOKIDAR_USEPOLLING=true

  volumes:
    - /app/node_modules
    - .:/app

  ports:
    - '80:80'
